### ISSUE TITLE
Font Awesome CSS 资源 403 了

### ISSUE THREAD

**Issue by AnotiaWang** [Pedro-null/halo-theme-hingle#2]
```
GET https://cdn.jsdelivr.net/gh/FortAwesome/Font-Awesome/css/font-awesome.min.css net::ERR_ABORTED 403
```

**Comment by Pedro-null** [comment]
主题在线更新一下再试试，替换了其他cdn链接

**Comment by AnotiaWang** [comment]
Telegram 的图标似乎显示不出来了

![image](https://user-images.githubusercontent.com/62269186/188461895-edccd535-fbe7-4fbe-8ec3-a848cf243a7b.png)

**Comment by Pedro-null** [comment]
再更新下，拿错版本了。。。。

**Comment by Pedro-null** [comment]
![image](https://user-images.githubusercontent.com/75029827/188483128-4007ab98-d9ab-4808-9931-0fd46ee44bcd.png)
