### ISSUE TITLE
头像问题——页面下方头像不显示

### ISSUE THREAD

**Issue by yikexiaoyao** [Pedro-null/halo-theme-hingle#4]
![Snipaste_2023-04-03_14-33-34](https://user-images.githubusercontent.com/36374114/229429618-e9d2f566-4f90-44c5-9bcf-ee4c83b6b554.png)

**Comment by Pedro-null** [comment]
页面下方显示的是博客logo，在 “博客设置” -> “常规设置” 的 logo 设置项，可以设置一下看看

**Comment by yikexiaoyao** [comment]
关于代码块彩虹字体样式请问后期有支持计划吗

**Comment by Pedro-null** [comment]
彩虹字体指的是？贴个图看看
